training:
  exp_name: "AEIC_ME_aigc"
  max_train_steps: 8000
  train_patch_size: 512
  train_batch_size_total: 8

  train_batch_size_per_gpu: 1
  gradient_accumulation_steps: 2   # 4 GPUs x 1 x 2 = 8

  save_num: 10
  eval_freq: 250
  max_grad_norm: 0.1
  dataloader_num_workers: 8
  checkpointing_steps: 1000

  base:
    lr: 2e-5
    lambda_rate: 4.0
    lambda_l2: 2.0
    lambda_dists: 1.0
    lambda_clip: 0.1
    lambda_adv: 0.1
    lambda_lpips: 1.0

  stages:
    - name: "stage_1"
      end_step: 4000

    - name: "stage_2"
      end_step: 6500
      lr: 1e-5

    - name: "stage_3"
      end_step: 7500
      lr: 5e-6

    - name: "stage_4"
      end_step: 1000000000000
      lr: 1e-6
